version: '3'
services:
  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - mongovolume:/data/db
    environment:
      - MONGO_DATA_DIR: /data/db
    ports:
      - 27017:27017

  web-services:
    container_name: web
    restart: unless-stopped
    build:
      context: ./web
    volumes:
      - ./web_dir/:/web/
      - build_folder:/web/build
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    ports:
      - 80:8000
    volumes:
      - build_folder:/var/www/web
    depends_on:
      - web-services

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/protheus.yml
    envirpment:
      - PROMETHEUS_COMMON_DISABLE_HTTP2
    depends_on:
      - web-services

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./datasource.yml/:/etc/grafana/provisioning/datasource.yml
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  mongovolume:
  build_folder: null
  grafana_data: {}
  